### PR TITLE
tocilizumab pathway results on Synovium tissue data

### PR DESCRIPTION
**Pull request by nrosed**
In this PR I update the pathway results after Tocilizumab treatment in RA. They are ordered by the most amount, to least about of changes.

New files
- **synovium_analysis/buddi_synovium_RitToc.ipynb** is the file that has all of the main results
- **synovium_analysis/buddi_synovium_RitToc_pred.ipynb** failed experiment that I want to keep around. Here I tried to predict treatment outcome using the embeddings

Updated / reran files
- **sc_preprocessing/0_qc_notebooks/scanpy_analysis_synovium_bulk.ipynb** qc of bulks, no big changes
- **sc_preprocessing/0_qc_notebooks/scanpy_analysis_synovium.ipynb** is qc -- not really changed from before, just updated the filtering
- **sc_preprocessing/2_make_pseudobulks/pseudobulk_synovium.ipynb** making the pseudobulks, no big changes
- **synovium_analysis/synovium_bulk_hyp_search_pred.ipynb** no big changes, just re-ran hypperparameter search

### CODE REVIEW

**Comment by ivichadriana** [comment]
some comments on things that need double checking, imports here and there, some explanation of the random forests classf, etc. not major.

**Review by ivichadriana — APPROVED** [review]

**Comment by nrosed** [comment]
<p>ah yes -- changed to "# number of drugs (CTRL, Tocilizumab, Rituximab)"</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546476'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>yeah -- i think its fine to keep</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546491'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546514'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>ack -- yes its overwritten in BuDDI method. I will fix it in that repo and make a new PR</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546531'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>yes, because this metadata table is joined across the single cell and bulk metadata tables. I added this comment to be clear to the user.</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546567'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>I added the following header to this section that states the goal of the prediction task:</p><p> </p><p> </p><p><strong>## Predict response using latent spaces</strong></p><p> </p><p> </p><p>In the following section we predicted how well we could use the latent spaces from BuDDI to predict treatment response <strong>**before**</strong> treatment.</p><p>We find that it does not work.</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546584'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546615'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546632'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546648'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546657'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546684'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>added more description</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546718'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>changed to # number of drugs (CTRL, Tocilizumab, Rituximab)</p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546735'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>updated</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546754'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>bug in BuDDI, will have a new PR in BuDDI with the fix</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546818'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>removed the sample ids</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546865'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>lol</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546808'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>no -- they use different indices to check random samples</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546795'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>ah, yes they are no longer only filtered to paired bulks here. I updated the comment</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546777'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>deleted</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/13/discussion/#comment-2040546548'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
