### PR TITLE
Response to reviewers

### PR DESCRIPTION
**Pull request by nrosed**
In this PR, I do a few small tweaks to the plotting code and add one new experiment.

This new experiment is to add a new testing data set across 3 cell lines and 5 drugs. The main pieces of code that need to be reviewed are 

- bayesprism_scripts/bayes_prism_sciplex.R
- l1000_sciplex_analysis/sciplex_bulk_hyp_search.ipynb
- l1000_sciplex_analysis/sciplex_comparators/sciplex_BP_analysis.ipynb
- l1000_sciplex_analysis/sciplex_comparators/sciplex_CVAE_analysis.ipynb
- l1000_sciplex_analysis/sciplex_comparators/sciplex_PCA_analysis.ipynb
- sc_preprocessing/0_qc_notebooks/scanpy_analysis_sciplex.ipynb

The other files can be reviewed if you have time, but they are either analyses files that did not work, but I want to keep, or small changes to existing files.

### CODE REVIEW

**Comment by ivichadriana** [comment]
done reviewing, feel free to merge!

**Comment by nrosed** [comment]
<p>:)</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438613338'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>I don't know why its like this! but i also thought it was interesting!</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438613357'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>deleted updated in <code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/0d611d968af705f27c120a83d40e0f9abb254cfd" target="_blank">0d611d9</a></code></p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438613284'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>ah yes good catch updated in <code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/0d611d968af705f27c120a83d40e0f9abb254cfd" target="_blank">0d611d9</a></code></p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438613302'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>oooo good catch deleted updated in <code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/0d611d968af705f27c120a83d40e0f9abb254cfd" target="_blank">0d611d9</a></code></p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438613319'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>deleted updated in <code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/0d611d968af705f27c120a83d40e0f9abb254cfd" target="_blank">0d611d9</a></code></p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438613274'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>yes -- in this simulation there should be no differences in log2FC and BayesPrism on average didn't make a mistake in this scenario.</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438620126'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>moved in <a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/4a742d6a26562156d66efb0c427b8827448b8579" target="_blank">4a742d6</a></p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438620108'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>deleted updated in <a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/4a742d6a26562156d66efb0c427b8827448b8579" target="_blank">4a742d6</a></p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438620057'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>good point -- removed and updated figures in <a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/4a742d6a26562156d66efb0c427b8827448b8579" target="_blank">4a742d6</a></p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438620093'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>went through and deleted, updated in </p><p> </p><p><code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/55f5ba605a6e104d0bb5e8cd73eda9f061f98ac2" target="_blank">55f5ba6</a></code></p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438620074'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>deleted, updated in. </p><p> </p><p><code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/55f5ba605a6e104d0bb5e8cd73eda9f061f98ac2" target="_blank">55f5ba6</a></code></p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438625086'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>ahhh - no i just did that when i was messing around with the notebook. I uncommented them, updated in </p><p> </p><p><code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/55f5ba605a6e104d0bb5e8cd73eda9f061f98ac2" target="_blank">55f5ba6</a></code></p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438625098'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>yes! I did this by design, so that the perturbation signal is actually hard to detect, so that's why PCA is so clean.</p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438628326'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p><a href="https://emojipedia.org/loudly-crying-face" target="_blank">😭</a></p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438631071'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
<p>deleted in </p><p> </p><p><code><a href="https://github.com/greenelab/buddi_analysis/pull/14/commits/636c7cc10059eb31b2e958142cf6c261b4d23e41" target="_blank">636c7cc</a></code></p><p> </p>

---

 <a href='https://app.reviewnb.com/greenelab/buddi_analysis/pull/14/discussion/#comment-2438628307'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nrosed** [comment]
Awesome, thanks so much!

**Pull request merged**
